### ISSUE TITLE
the pretrained model weights

### ISSUE THREAD

**Issue by llj110** [Visual-AI/SPTNet#15]
How can I load the parameters for both the backbone and projector together? I can only load the backbone parameters, and loading both results in an error, even when using the full checkpoint which contains weights for both the backbone and projection head

**Comment by whj363636** [comment]
Hi @llj110 

Thanks for your interest. The backbone and projector components have been wrapped in a Sequential module called "classifier," while the prompter and classifier are further grouped within another Sequential module called 'model'. Therefore, if your intention is to solely reload the weights for the 'classifier' component, rather than the entire 'model', in both train.py and eval.py, you can maintain the code and simply select the last module from the pretrained model. This module contains the full weights of the backbone and projector.

**Comment by llj110** [comment]
classifier = nn.Sequential(backbone, projector).cuda()
state_dict = torch.load(args.pretrained_model_path, map_location='cpu')
classifier.load_state_dict(state_dict)
Thanks for your reply. My question is how to load the pretrained model parameters for the classifier using dino_vitbase16_pretrain.pth. The model I downloaded can only load the backbone parameters, but the parameters for the DINOHead cannot be loaded. This issue persists even when I use dino_vitbase16_pretrain_full_checkpoint.pth, which contains the weights for both the backbone and the projector head.

**Comment by llj110** [comment]
I can just run this code  by adjust the code to 
state_dict = torch.load(args.pretrained_model_path, map_location='cpu')
backbone.load_state_dict(state_dict)
classifier = nn.Sequential(backbone, projector).cuda(). Therefore, I would like to ask if it is possible to provide the pretrained weights for the classifier.

**Comment by whj363636** [comment]
I see. Please refer to #4.

**Comment by llj110** [comment]
Thanks for your valuable reply. I will try to obtain the pretrained SimGCD model

**Comment by Si-yu-Wang** [comment]
classifier = nn.Sequential(backbone, projector).cuda()
state_dict = torch.load(args.pretrained_model_path, map_location='cpu')
classifier.load_state_dict(state_dict)
Sorry, I also have a question. I already had got the pretrained model(SimGCD on cifar 10), but it also could not load the full model. I would like to ask that should I change the code?
