### ISSUE TITLE
About the checkpoints of CIFAR-100

### ISSUE THREAD

**Issue by wendy26zhang** [Visual-AI/SPTNet#16]
Thanks for your great work. I downloaded the checkpoints file you provided and found there is a problem with the [cifar10&100 checkpoints](https://drive.google.com/drive/folders/16O0QvsCuVb9Xd-UJNx3J3n6WVH6B_IHw) running on eval.py. Did you accidentally provide the wrong weight file, or do I need to modify the code before it run? Looking forward to your reply.
**The results of CIFAR-100**
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 118/118 [01:17<00:00,  1.53it/s]
Epoch 0, Train ACC Unlabelled_v2: All 0.1460 | Old 0.1101 | New 0.2177
Best Accuracies: All 0.1460 | Old 0.1101 | New 0.2177

**The results of CIFAR-10**
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 147/147 [01:38<00:00,  1.50it/s]
Epoch 0, Train ACC Unlabelled_v2: All 0.4842 | Old 0.2973 | New 0.5777
Best Accuracies: All 0.4842 | Old 0.2973 | New 0.5777

**Comment by whj363636** [comment]
Hi @wei26zhang,

Thanks for your interest. Upon reviewing the checkpoints, I have confirmed that they are correct. However, the issue lies in the hyper-parameter name (i.e. pretrained_model_path) and the prompt type specified in the scripts. If you encounter a mismatch error while loading the pretrained model, please use 'patch' as the value for the 'prompt_type' hyperparameter. Both 'all' and 'patch' prompt types yield similar performance for CIFAR-10 and CIFAR-100. Please kindly utilize the latest version of eval.py and the corresponding script to perform the evaluation.

![image](https://github.com/Visual-AI/SPTNet/assets/8454140/0b380f13-7e49-482c-8c6c-95b15937d5de)
![image](https://github.com/Visual-AI/SPTNet/assets/8454140/27c7dc77-fa03-4084-b072-4724c108ee38)

**Comment by whj363636** [comment]
I also notice that the logs you provided contain 'Epoch 0', showing that you're using the train.py. Please use eval.py to perform evaluation if you would like to test the pretrained models of SPTNet.

**Comment by wendy26zhang** [comment]
Thank you for your reply. I try to use 'patch' as the value for the 'prompt_type' hyperparameter and get the right results. Thanks a lot.

**Comment by wei26zhang** [comment]
Thank you for your reply. I try to use 'patch' as the value for the 'prompt_type' hyper-parameter and get the right results. Thanks a lot

**Comment by whj363636** [comment]
Great to know that. I will close the issue. Feel free to reopen it if you meet the difficulty.
